[package]
name = "gwe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
